// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "grayColors": string;
      "highlightMappings": string;
      "fieldCategory": boolean;
      "fieldWord": boolean;
      "fieldPaperTitle": boolean;
      "fieldExcerptDate": boolean;
      "fieldTranslation": boolean;
      "fieldContextSentence": boolean;
      "fieldPageLabel": boolean;
      "records": string;
      "lastCapturedAt": string;
      "historyScanVersion": string;
      "historyScannedAt": string;
    };
  }
}
